Change detection for art installation

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -80,8 +80,10 @@ EOF
 
 }
 
-[ -z $(which autoremove-torrents) ] && { echo -e "ERROR: AutoRemove-Torrents is NOT installed" ; exit 1 ; }
-
+if version_ge $($(which autoremove-torrents) -v -l /tmp 2>&1 | head -1 | grep -oP "[0-9.]+" | tail -1) 1.5.2 ; then
+    echo -e "ERROR: AutoRemove-Torrents is NOT installed"
+    exit 1
+fi
 echo_task "Setting $AppName Alias ..."
 alias_art & spinner $!
 status_done
