Add detection for art installation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -169,6 +169,11 @@ function configure_art() {
 
 }
 
-echo_task "Configuring $AppName ..."
-configure_art & spinner $!
-check_status $status_lock
+if version_ge $($(which autoremove-torrents) -v -l /tmp 2>&1 | head -1 | grep -oP "[0-9.]+" | tail -1) 1.5.2 ; then
+    echo_task "Configuring $AppName ..."
+    configure_art & spinner $!
+    check_status $status_lock
+else
+    echo -e "ERROR: AutoRemove-Torrents is NOT installed"
+    exit 1
+fi
